### ISSUE TITLE
clarify on input variables in xconv()

### ISSUE THREAD

**Issue by amiltonwong** [yangyanli/PointCNN#31]
Hi, authors,

In funtion [xconv()](https://github.com/yangyanli/PointCNN/blob/master/pointcnn.py#L10) , there are many input variables. Could you help to clarify their meaning? According to PointCNN paper. I guess them as follows. Pls help to correct them if there's any mistake:

```
input: 
    pts: input points, (neighborhood) point matrix
    fts: input point features, (neighborhood point) feature matrix
    qrs: representative points
    K: nunmber of neighboring points around representative point by K-Nearest Neighbors search
    N: number of output points
    P:  ??
    D: dilation rate
    C: channels of output feature, equals to C_2 in paper
    C_pts_fts: channels of input feature, equals to C_delta + C_1 in paper
```

Moreover, what does "P" means ?

THX!
